name: build and release

on:
  push:
    tags: ['*']
  # workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: build
        run: |
          yarn
        #  npx tsc main.ts --declaration # 不用编译, 因为已经编译好了
      - name: archive
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: koishi-plugin-qtail.zip
          directory: .
          exclusions: '.github/* .gitignore .npmignore'
      - name: Upload release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "koishi-plugin-qtail.zip"
          artifactContentType: "application/zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
